use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'LZDependencyToolkit_Example' do
  pod 'LZDependencyToolkit', :path => '../'

  target 'LZDependencyToolkit_Tests' do
    inherit! :search_paths
    
  end
end
