use_frameworks!
platform :ios, '8.0'

target 'LZDependencyToolkit_Example' do
  pod 'LZDependencyToolkit', :path => '../'

  target 'LZDependencyToolkit_Tests' do
    inherit! :search_paths

    
  end
end
